apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test-success
  name: ship-ui-test-ol3of
spec:
  containers:
  - command:
    - /tools/bats/bats
    - -t
    - /tests/run.sh
    image: lachlanevenson/k8s-kubectl:v1.4.8-bash
    name: ship-ui-test
    volumeMounts:
    - mountPath: /tests
      name: tests
      readOnly: true
    - mountPath: /tools
      name: tools
  initContainers:
  - command:
    - bash
    - -c
    - |
      set -ex
      # copy bats to tools dir
      cp -R /usr/local/libexec/ /tools/bats/
    image: dduportal/bats:0.4.0
    name: test-framework
    volumeMounts:
    - mountPath: /tools
      name: tools
  restartPolicy: Never
  volumes:
  - configMap:
      name: ship-consul-tests
    name: tests
  - emptyDir: {}
    name: tools
