---
# Source: consul/templates/gossip-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: ship-consul-gossip-key
  labels:
    heritage: "Tiller"
    release: "ship"
    chart: consul-3.5.3
    component: "ship-consul"
type: Opaque
data:
  
  gossip-key: NDduYW5idjY0QXhPa1JyQTc3Rkp0amFO
  

