---
# Source: consul/templates/ui-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: "ship-consul-ui"
  labels:
    heritage: "Tiller"
    release: "ship"
    chart: consul-3.5.3
    component: "ship-consul"
spec:
  ports:
  - name: http
    port: 8500
  selector:
    component: "ship-consul"
  type: "NodePort"
