---
# Source: ds/templates/ds.yaml
# Copyright (c) 2016-2018 ForgeRock AS. All Rights Reserved.
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ds
  labels:
    instance: ds
    app: ds-ds
    vendor: forgerock
    component: ds
    release: ds
    heritage: Tiller
spec:
  serviceName: ds
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: db
      annotations:
        pv.beta.kubernetes.io/gid: "11111"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  template:
    metadata:
      labels:
        instance: ds
        app: ds-ds
        vendor: forgerock
        release: ds
        component: ds
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: instance
                  operator: In
                  values:
                  - ds
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      # This will make sure the mounted PVCs are writable by the forgerock user with gid 111111.
      securityContext:
        fsGroup: 11111
        runAsUser: 11111
        supplementalGroups:
        - 0
        
      initContainers: []
      
      containers:
      - name: ds
        image:  forgerock-docker-public.bintray.io/forgerock/ds:6.5.0
        imagePullPolicy: IfNotPresent
        #terminationGracePeriodSeconds: 10
        resources:
            limits:
              memory: 768Mi
            requests:
              memory: 512Mi
            
        envFrom:
        - configMapRef:
            name: ds
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 1389
          name: ldap
        - containerPort: 4444
          name: admin
        - containerPort: 8989
          name: replication
        - containerPort: 8080
          name: metrics
        volumeMounts:
        - name: dj-secrets
          mountPath: /var/run/secrets/opendj
        - name: backup
          mountPath: /opt/opendj/bak
        - name: logs
          mountPath: /opt/opendj/logs
        - name: db
          mountPath: /opt/opendj/data
        args: [ "start" ]
        # Due to cost, we don't want to do a full scrape of the metrics http endpoint - so we create a tcp connection
        # todo: revisit when https://bugster.forgerock.org/jira/browse/OPENDJ-4728 is resolved.
        # TODO: Uncomment when we get ds to start faster. Seletively disable replication
        # readinessProbe:
        #   tcpSocket:
        #     port: metrics
        #   periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: metrics
          initialDelaySeconds: 60
          periodSeconds: 120
      volumes:
      - name: dj-secrets
        secret:
          secretName: ds
      - name: logs
        emptyDir: {}
      - name: backup
        emptyDir: {}
      
