---
# Source: ds/templates/service.yaml
# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
apiVersion: v1
kind: Service
metadata:
  name: ds
  labels:
    app: ds
    component: ds
    vendor: forgerock
    heritage: Tiller
spec:
  clusterIP: None
  ports:
    - port: 1389
      name: ldap
      targetPort: 1389
    - port: 4444
      name: djadmin
      targetPort: 4444
    - port: 1636
      name: ldaps
      targetPort: 1636
    - port: 8080
      protocol: TCP
      name: metrics
  selector:
    app: ds-ds
    release: ds
