kind: ""
apiversion: ""
patchesJson6902:
- target:
    group: apps
    version: v1beta2
    kind: Deployment
    name: version
  path: chart-patch.json
- target:
    group: apps
    version: v1beta2
    kind: Deployment
    name: version
  path: heritage-patch.json
- target:
    version: v1
    kind: Service
    name: version
  path: chart-patch.json
- target:
    version: v1
    kind: Service
    name: version
  path: heritage-patch.json
bases:
- ../../base
