kind: ""
apiversion: ""
patchesStrategicMerge:
- redis-master-service.yaml
- redis-slave-service.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: redis-slave
  path: container-name-patch.json
bases:
- ../defaults
