bases:
- ../../base
patchesJson6902:
- path: chart-patch.json
  target:
    group: extensions
    kind: Deployment
    name: factorio-factorio
    version: v1beta1
- path: heritage-patch.json
  target:
    group: extensions
    kind: Deployment
    name: factorio-factorio
    version: v1beta1
- path: chart-patch.json
  target:
    kind: Service
    name: factorio-factorio
    version: v1
- path: heritage-patch.json
  target:
    kind: Service
    name: factorio-factorio
    version: v1
- path: chart-patch.json
  target:
    kind: PersistentVolumeClaim
    name: factorio-factorio-savedgames
    version: v1
- path: heritage-patch.json
  target:
    kind: PersistentVolumeClaim
    name: factorio-factorio-savedgames
    version: v1
- path: chart-patch.json
  target:
    kind: Secret
    name: factorio-factorio
    version: v1
- path: heritage-patch.json
  target:
    kind: Secret
    name: factorio-factorio
    version: v1
