bases:
- ../../base
patchesJson6902:
- path: chart-patch.json
  target:
    group: extensions
    kind: DaemonSet
    name: jaeger-agent
    version: v1beta1
- path: heritage-patch.json
  target:
    group: extensions
    kind: DaemonSet
    name: jaeger-agent
    version: v1beta1
- path: chart-patch.json
  target:
    kind: Service
    name: jaeger-agent
    version: v1
- path: heritage-patch.json
  target:
    kind: Service
    name: jaeger-agent
    version: v1
- path: chart-patch.json
  target:
    group: batch
    kind: Job
    name: jaeger-cassandra-schema
    version: v1
- path: heritage-patch.json
  target:
    group: batch
    kind: Job
    name: jaeger-cassandra-schema
    version: v1
- path: chart-patch.json
  target:
    kind: Service
    name: jaeger-cassandra
    version: v1
- path: heritage-patch.json
  target:
    kind: Service
    name: jaeger-cassandra
    version: v1
- path: chart-patch.json
  target:
    group: apps
    kind: StatefulSet
    name: jaeger-cassandra
    version: v1
- path: heritage-patch.json
  target:
    group: apps
    kind: StatefulSet
    name: jaeger-cassandra
    version: v1
- path: chart-patch.json
  target:
    group: extensions
    kind: Deployment
    name: jaeger-collector
    version: v1beta1
- path: heritage-patch.json
  target:
    group: extensions
    kind: Deployment
    name: jaeger-collector
    version: v1beta1
- path: chart-patch.json
  target:
    kind: Service
    name: jaeger-collector
    version: v1
- path: heritage-patch.json
  target:
    kind: Service
    name: jaeger-collector
    version: v1
- path: chart-patch.json
  target:
    kind: ConfigMap
    name: jaeger
    version: v1
- path: heritage-patch.json
  target:
    kind: ConfigMap
    name: jaeger
    version: v1
- path: chart-patch.json
  target:
    group: extensions
    kind: Deployment
    name: jaeger-query
    version: v1beta1
- path: heritage-patch.json
  target:
    group: extensions
    kind: Deployment
    name: jaeger-query
    version: v1beta1
- path: chart-patch.json
  target:
    kind: Service
    name: jaeger-query
    version: v1
- path: heritage-patch.json
  target:
    kind: Service
    name: jaeger-query
    version: v1
