apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: redis2
  name: redis2
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis2
  template:
    metadata:
      labels:
        component: redis2
    spec:
      containers:
      - image: redis
        name: redis2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
      - image: redis
        name: redis
