bases:
- ../../base
patchesJson6902:
- path: chart-patch.json
  target:
    kind: ConfigMap
    name: kibana
    version: v1
- path: heritage-patch.json
  target:
    kind: ConfigMap
    name: kibana
    version: v1
- path: chart-patch.json
  target:
    group: apps
    kind: Deployment
    name: kibana
    version: v1beta1
- path: heritage-patch.json
  target:
    group: apps
    kind: Deployment
    name: kibana
    version: v1beta1
- path: chart-patch.json
  target:
    kind: Service
    name: kibana
    version: v1
- path: heritage-patch.json
  target:
    kind: Service
    name: kibana
    version: v1
