kind: ""
apiversion: ""
patchesJson6902:
- target:
    version: v1
    kind: ConfigMap
    name: kibana
  path: chart-patch.json
- target:
    version: v1
    kind: ConfigMap
    name: kibana
  path: heritage-patch.json
- target:
    group: apps
    version: v1beta1
    kind: Deployment
    name: kibana
  path: chart-patch.json
- target:
    group: apps
    version: v1beta1
    kind: Deployment
    name: kibana
  path: heritage-patch.json
- target:
    version: v1
    kind: Service
    name: kibana
  path: chart-patch.json
- target:
    version: v1
    kind: Service
    name: kibana
  path: heritage-patch.json
bases:
- ../../base
