apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
      - args:
        - --appendonly
        - "yes"
        image: redis
        name: redis
