bases:
- ../../installer/base
patchesJson6902:
- path: chart-patch.json
  target:
    kind: Service
    name: ship-consul
    version: v1
- path: heritage-patch.json
  target:
    kind: Service
    name: ship-consul
    version: v1
- path: chart-patch.json
  target:
    group: apps
    kind: StatefulSet
    name: ship-consul
    version: v1beta1
- path: heritage-patch.json
  target:
    group: apps
    kind: StatefulSet
    name: ship-consul
    version: v1beta1
- path: chart-patch.json
  target:
    kind: Secret
    name: ship-consul-gossip-key
    version: v1
- path: heritage-patch.json
  target:
    kind: Secret
    name: ship-consul-gossip-key
    version: v1
- path: chart-patch.json
  target:
    group: policy
    kind: PodDisruptionBudget
    name: ship-consul-pdb
    version: v1beta1
- path: heritage-patch.json
  target:
    group: policy
    kind: PodDisruptionBudget
    name: ship-consul-pdb
    version: v1beta1
- path: chart-patch.json
  target:
    kind: Service
    name: ship-consul-ui
    version: v1
- path: heritage-patch.json
  target:
    kind: Service
    name: ship-consul-ui
    version: v1
