kind: ""
apiversion: ""
patchesJson6902:
- target:
    group: apps
    version: v1beta1
    kind: StatefulSet
    name: ds
  path: heritage-patch.json
- target:
    version: v1
    kind: Service
    name: ds
  path: heritage-patch.json
bases:
- ../../base
